### ISSUE TITLE
Cadence 0.5.1 and 0.5.2 charts appear broken - Connection refused from frontend nodes

### ISSUE THREAD

**Issue by AngerM-DD** [banzaicloud/banzai-charts#1001]
**Describe the bug**
Testing the helm charts using a local docker k8s cluster with a basic config (values.yml only specifies the 0.10.3 image tag) and then using `k8s port-forward` to be able to talk to the cluster I only get connection refused from the cadence sample apps. If I pass `--version 0.5.0` using the same values.yml to my helm install the cluster works as expected.

**Steps to reproduce the issue:**
```
$ cat values.yml
server:
  image:
    tag: 0.10.3
$ helm repo update
$ helm install -f values.yml cadence banzaicloud-stable/cadence
<attempt to use cluster and it fails>
$ helm uninstall cadence
$ helm install -f values.yml cadence banzaicloud-stable/cadence --version 0.5.0
<attempt to use cluster and it works>
```

**Expected behavior**

**Screenshots**
```
$ k8s port-forward service/cadence-frontend 7933:7933
Forwarding from 127.0.0.1:7933 -> 7933
Forwarding from [::1]:7933 -> 7933
Handling connection for 7933
E0110 12:37:23.458001   50397 portforward.go:400] an error occurred forwarding 7933 -> 7933: error forwarding port 7933 to pod e8b78eee7d091308b4ff67785e655d74921faa2bafd35040b30e8467a737295b, uid : exit status 1: 2020/01/10 20:37:23 socat[21515] E connect(16, AF=2 127.0.0.1:7933, 16): Connection refused
Handling connection for 7933
```
```
$ JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home ./gradlew -q execute -PmainClass=com.uber.cadence.samples.common.RegisterDomain
Exception in thread "main" org.apache.thrift.TException: Rpc error:<ErrorResponse id=-1 errorType=NetworkError message=Connection timeout on identification: /127.0.0.1:7933/cadence-frontend::WorkflowService::RegisterDomain>
        at com.uber.cadence.serviceclient.WorkflowServiceTChannel.throwOnRpcError(WorkflowServiceTChannel.java:513)
        at com.uber.cadence.serviceclient.WorkflowServiceTChannel.doRemoteCall(WorkflowServiceTChannel.java:488)
        at com.uber.cadence.serviceclient.WorkflowServiceTChannel.registerDomain(WorkflowServiceTChannel.java:575)
        at com.uber.cadence.serviceclient.WorkflowServiceTChannel.lambda$RegisterDomain$2(WorkflowServiceTChannel.java:566)
        at com.uber.cadence.serviceclient.WorkflowServiceTChannel.lambda$measureRemoteProc$1(WorkflowServiceTChannel.java:559)
        at com.uber.cadence.serviceclient.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:533)
        at com.uber.cadence.serviceclient.WorkflowServiceTChannel.measureRemoteProc(WorkflowServiceTChannel.java:556)
        at com.uber.cadence.serviceclient.WorkflowServiceTChannel.RegisterDomain(WorkflowServiceTChannel.java:566)
        at com.uber.cadence.samples.common.RegisterDomain.main(RegisterDomain.java:45)
<==========---> 80% EXECUTING [14s]
> :execute
```

**Additional context**

**Comment by AngerM-DD** [comment]
My docker-desktop about which is running the local k8s cluster:
![image](https://user-images.githubusercontent.com/58711323/72186023-19966e00-33a9-11ea-87bd-efed0dc72891.png)

**Comment by sagikazarmark** [comment]
Thanks for reporting the issue. We will take a look at it and get back to you.

**Comment by sagikazarmark** [comment]
@AngerM-DD Unfortunately this is a byproduct of the Pod IP binding introduced in #997.

Since without that change scaling Cadence components is not possible at the moment, we have to find alternative solutions. Looks like `kubectl port-forward` can't handle Pod IP binds (I'm guessing it doesn't go directly through the Pod IP)

One alternative is setting up a socat sidecar. I'd rather not add that to the chart though.

Here is an example that worked for me:

```
helm install stable/socat-tunneller --name cadence-frontent-tunnel --set tunnel.host=cadence-frontend --set tunnel.port=7933 --set nameOverride=cadence-frontent-tunnel
```

I'm gonna add this snippet to the chart readme.

Not sure if there is a better solution at the moment.
