### ISSUE TITLE
Extend History Server chart to add / to log directory path

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/banzai-charts#431]
We should support adding / to the end of logdirectory path if it's not set by the user.
Otherwise the HS will fail with:
```Caused by: java.io.FileNotFoundException: Log directory specified does not exist: s3a://testbucket1
	at org.apache.spark.deploy.history.FsHistoryProvider.org$apache$spark$deploy$history$FsHistoryProvider$$startPolling(FsHistoryProvider.scala:214)
	at org.apache.spark.deploy.history.FsHistoryProvider.initialize(FsHistoryProvider.scala:160)
	at org.apache.spark.deploy.history.FsHistoryProvider.<init>(FsHistoryProvider.scala:156)
	at org.apache.spark.deploy.history.FsHistoryProvider.<init>(FsHistoryProvider.scala:78)
	... 6 more
```

**Comment by baluchicken** [comment]
This will be handled from code in HS
